FROM node
WORKDIR /back
COPY . .
                                                                                                                                                                                             
RUN npm install                                                                                                                                                                                 

CMD ["npm", "start"]